root: true
env:
  browser: true
  es6: true
extends:
  - plugin:import/recommended
  - plugin:import/typescript
  - airbnb-typescript
  - prettier
  - prettier/react
  - prettier/@typescript-eslint
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 7
  sourceType: module
  project: tsconfig.eslint.json
plugins:
  - eslint-plugin-react-hooks
  - '@typescript-eslint/eslint-plugin'
ignorePatterns:
  - 'build/**/*'
  - '**/esm/*'
  - '**/cjs/*'
  - '**/types/*'
rules:
  no-bitwise:
    - error
    - allow:
      - '|'
      - '&'
      - '|='
      - '&='
  no-param-reassign:
    - error
    - props: false
  class-methods-use-this:
    - error
    - exceptMethods:
      - validateInternal
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  import/prefer-default-export:
    - off
  no-underscore-dangle:
    - off
  no-nested-ternary:
    - off
  '@typescript-eslint/naming-convention':
    - error
    - selector:
        - function
      format:
        - camelCase
        - PascalCase
      leadingUnderscore: allow
overrides:
  - files:
      - 'tests/**/*.{ts,tsx}'
    rules:
      '@typescript-eslint/lines-between-class-members':
        - off
      '@typescript-eslint/no-unused-vars':
        - error
        - argsIgnorePattern: '^_'
      max-classes-per-file:
        - off
      'react/prefer-stateless-function':
        - off
