root: true
env:
  browser: true
  es6: true
extends:
  - plugin:import/recommended
parserOptions:
  ecmaVersion: 7
  sourceType: module
plugins:
  - eslint-plugin-react-hooks
ignorePatterns:
  - '**.ejs'
  - '**.yml'
  - '/build/**'
  - '/coverage/**'
  - '/dist/**'
  - '/examples/**'
  - '**/esm/**'
  - '**/cjs/**'
  - '**/types/**'
overrides:
  - files:
      - '**.{js,mjs}'
    extends:
      - airbnb
      - prettier
  - files:
      - '**.{ts,tsx}'
    extends:
      - plugin:import/typescript
      - airbnb-typescript
      - prettier
      - prettier/react
      - prettier/@typescript-eslint
    parser: '@typescript-eslint/parser'
    parserOptions:
      ecmaVersion: 7
      sourceType: module
      project: tsconfig.eslint.json
    plugins:
      - '@typescript-eslint/eslint-plugin'
    rules:
      no-bitwise:
        - error
        - allow:
          - '|'
          - '&'
          - '|='
          - '&='
      no-param-reassign:
        - error
        - props: false
      class-methods-use-this:
        - error
        - exceptMethods:
          - validateInternal
      no-plusplus:
        - error
        - allowForLoopAfterthoughts: true
      import/prefer-default-export:
        - off
      no-underscore-dangle:
        - off
      no-nested-ternary:
        - off
      '@typescript-eslint/naming-convention':
        - error
        - selector:
            - function
          format:
            - camelCase
            - PascalCase
          leadingUnderscore: allow
