root: true
env:
  browser: true
  es6: true
parser: '@babel/eslint-parser'
parserOptions:
  sourceType: module
extends:
  - plugin:import/recommended
  - airbnb
  - prettier
overrides:
  - files: src/**.{js,jsx}
    rules:
      'import/no-extraneous-dependencies':
        - off
      max-classes-per-file:
        - off
      react/prop-types:
        - off
