root: true
env:
  browser: true
  es6: true
parser: '@babel/eslint-parser'
parserOptions:
  sourceType: module
extends:
  - plugin:import/recommended
  - airbnb
  - prettier
  - prettier/react
rules:
  'import/no-extraneous-dependencies':
    - off
