root: true
env:
  browser: true
  es6: true
extends:
  - plugin:import/recommended
  - plugin:import/typescript
  - airbnb-typescript
  - prettier
  - prettier/react
  - prettier/@typescript-eslint
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 7
  sourceType: module
  project: tsconfig.eslint.json
plugins:
  - eslint-plugin-react-hooks
  - '@typescript-eslint/eslint-plugin'
