on:
  push:
    branches-ignore:
      - gh-pages
    paths-ignore:
      - 'examples/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'examples/**'
      - '**.md'
name: CI
jobs:
  build:
    name: Node v14 on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - run: npm run test:all
