on:
  push:
    branches-ignore:
      - gh-pages
    paths-ignore:
      - 'examples/**'
      - '**.md'
name: Coveralls
jobs:
  build:
    name: Coveralls - Node v14 on ubuntu-latest
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - run: npm run coverage:all
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
